#############################################################################
# Makefile for building: geysercoin-qt
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 11. ??? 22:39:26 2018
# Project:  GeyserCoin-Qt.pro
# Template: app
# Command: c:/qt4/bin/qmake.exe USE_QRCODE=1 USE_UPNP=1 USE_IPV6=1 -o Makefile GeyserCoin-Qt.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = c:/qt4/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = cp -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: GeyserCoin-Qt.pro  ../qt4/mkspecs/default/qmake.conf ../qt4/mkspecs/features/device_config.prf \
		../qt4/mkspecs/qconfig.pri \
		../qt4/mkspecs/features/qt_functions.prf \
		../qt4/mkspecs/features/qt_config.prf \
		../qt4/mkspecs/win32-g++/qmake.conf \
		../qt4/mkspecs/win32-g++-4.6/qmake.conf \
		../qt4/mkspecs/features/exclusive_builds.prf \
		../qt4/mkspecs/features/default_pre.prf \
		../qt4/mkspecs/features/win32/default_pre.prf \
		../qt4/mkspecs/features/release.prf \
		../qt4/mkspecs/features/debug_and_release.prf \
		../qt4/mkspecs/features/default_post.prf \
		../qt4/mkspecs/features/win32/default_post.prf \
		../qt4/mkspecs/features/static.prf \
		../qt4/mkspecs/features/win32/thread.prf \
		../qt4/mkspecs/features/win32/rtti.prf \
		../qt4/mkspecs/features/win32/exceptions.prf \
		../qt4/mkspecs/features/win32/stl.prf \
		../qt4/mkspecs/features/warn_on.prf \
		../qt4/mkspecs/features/qt.prf \
		../qt4/mkspecs/features/moc.prf \
		../qt4/mkspecs/features/win32/windows.prf \
		../qt4/mkspecs/features/resources.prf \
		../qt4/mkspecs/features/uic.prf \
		../qt4/mkspecs/features/yacc.prf \
		../qt4/mkspecs/features/lex.prf \
		c:/qt4/lib/qtmain.prl \
		c:/qt4/lib/QtGui.prl \
		c:/qt4/lib/QtNetwork.prl \
		c:/qt4/lib/QtCore.prl
	$(QMAKE) USE_QRCODE=1 USE_UPNP=1 USE_IPV6=1 -o Makefile GeyserCoin-Qt.pro
../qt4/mkspecs/features/device_config.prf:
../qt4/mkspecs/qconfig.pri:
../qt4/mkspecs/features/qt_functions.prf:
../qt4/mkspecs/features/qt_config.prf:
../qt4/mkspecs/win32-g++/qmake.conf:
../qt4/mkspecs/win32-g++-4.6/qmake.conf:
../qt4/mkspecs/features/exclusive_builds.prf:
../qt4/mkspecs/features/default_pre.prf:
../qt4/mkspecs/features/win32/default_pre.prf:
../qt4/mkspecs/features/release.prf:
../qt4/mkspecs/features/debug_and_release.prf:
../qt4/mkspecs/features/default_post.prf:
../qt4/mkspecs/features/win32/default_post.prf:
../qt4/mkspecs/features/static.prf:
../qt4/mkspecs/features/win32/thread.prf:
../qt4/mkspecs/features/win32/rtti.prf:
../qt4/mkspecs/features/win32/exceptions.prf:
../qt4/mkspecs/features/win32/stl.prf:
../qt4/mkspecs/features/warn_on.prf:
../qt4/mkspecs/features/qt.prf:
../qt4/mkspecs/features/moc.prf:
../qt4/mkspecs/features/win32/windows.prf:
../qt4/mkspecs/features/resources.prf:
../qt4/mkspecs/features/uic.prf:
../qt4/mkspecs/features/yacc.prf:
../qt4/mkspecs/features/lex.prf:
c:\qt4\lib\qtmain.prl:
c:\qt4\lib\QtGui.prl:
c:\qt4\lib\QtNetwork.prl:
c:\qt4\lib\QtCore.prl:
qmake: qmake_all FORCE
	@$(QMAKE) USE_QRCODE=1 USE_UPNP=1 USE_IPV6=1 -o Makefile GeyserCoin-Qt.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) C:/geysercoin-master/src/leveldb/libleveldb.a;
	-$(DEL_FILE) cd
	-$(DEL_FILE) C:/geysercoin-master/src/leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) $(MAKE)
	-$(DEL_FILE) clean
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

C:/geysercoin-master/src/leveldb/libleveldb.a: FORCE
	cd C:/geysercoin-master/src/leveldb && CC=gcc CXX=g++ TARGET_OS=OS_WINDOWS_CROSSCOMPILE $(MAKE) OPT="-pipe -fno-keep-inline-dllexport -O2" libleveldb.a libmemenv.a && ranlib C:/geysercoin-master/src/leveldb/libleveldb.a && ranlib C:/geysercoin-master/src/leveldb/libmemenv.a

check: first

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
